### ISSUE TITLE
About "create folder" function

### ISSUE THREAD

**Issue by minshifu** [Jahn08/WEB-PAGE-HIGHLIGHTER#1]
Thank you for your work.I was wonderting if you could add "create folder" function to help users better sort out saved pages (in differently named folders). Also, could you please let users set and change local directory for saved pages? 

Thank you and best regards!

**Comment by Jahn08** [comment]
Hello, @minshifu! Thank you for your feedback and your suggestions! 
Sorry that it took me a long time to answer - apparently, my notifications on GitHub hasn't been set up properly until now.
The first proposition might indeed make sense and I'll try to give it a go before too long.
As for the second point, I haven't taken it in entirely. Do you mean, if there are going to be folders (your first suggestion) then the user should be able to opt for an active one in the settings?

**Comment by Jahn08** [comment]
The functionality of categorising pages was added in the #2 pull request. After some additional changes the enhancement has been submitted as a part of a new version (1.1.0) to the Mozilla (it's already available there) and Chrome (it's under review and is due to be published in about a week) extension stores.
